In [12]:
from gaussian_process.regression import GaussianProcessRegressor
from gaussian_process.kernels import RBF
import jax.numpy as jnp
import jax
import matplotlib.pyplot as plt

In [13]:
# model = GaussianProcessRegressor(RBF(),1,(1,))

In [14]:
# X_data = jnp.ones((2,2))
# Y_data = jnp.ones((2,2))

# model.fit(X_data,Y_data)

In [15]:
# X = jnp.zeros((1,2))
# model.predict(X,True)

In [16]:
# a = jnp.arange(10,dtype=jnp.float32) // 3
# a = a.astype(jnp.int32)

In [17]:
# a.dtype

In [18]:
from jax import vmap
from functools import partial
@partial(vmap, in_axes=(0,None))
@partial(vmap, in_axes=(None,0))
def f(x,y):
    return jnp.dot(x-y,x-y)

In [19]:
X = jnp.arange(5,dtype=jnp.float32).reshape(-1,1)
Y = jnp.arange(5,dtype=jnp.float32).reshape(-1,1)
print(X)
print(Y)
print(f(X,Y))

[[0.]
 [1.]
 [2.]
 [3.]
 [4.]]
[[0.]
 [1.]
 [2.]
 [3.]
 [4.]]
[[ 0.  1.  4.  9. 16.]
 [ 1.  0.  1.  4.  9.]
 [ 4.  1.  0.  1.  4.]
 [ 9.  4.  1.  0.  1.]
 [16.  9.  4.  1.  0.]]


In [20]:
from gaussian_process.kernels import RBF

In [21]:
class Test:
    def __init__(self) -> None:
        self.kernel = RBF()

    @partial(vmap, in_axes=(None,0,None,None))
    @partial(vmap, in_axes=(None,None,0,None))
    def f(self,x,y,index):
        return self.kernel.eval_dx2(x,y,index)

In [22]:
T = Test()
print(T.f(X,X,0))

[[ 0.         -0.60653067 -0.27067056 -0.03332699 -0.00134185]
 [ 0.60653067  0.         -0.60653067 -0.27067056 -0.03332699]
 [ 0.27067056  0.60653067  0.         -0.60653067 -0.27067056]
 [ 0.03332699  0.27067056  0.60653067  0.         -0.60653067]
 [ 0.00134185  0.03332699  0.27067056  0.60653067  0.        ]]
