In [1]:
from gaussian_process.regression import GaussianProcessRegressor
from gaussian_process.kernels import RBF
import jax.numpy as jnp
import jax
import matplotlib.pyplot as plt

In [2]:
# model = GaussianProcessRegressor(RBF(),1,(1,))

In [3]:
# X_data = jnp.ones((2,2))
# Y_data = jnp.ones((2,2))

# model.fit(X_data,Y_data)

In [4]:
# X = jnp.zeros((1,2))
# model.predict(X,True)

In [5]:
# a = jnp.arange(10,dtype=jnp.float32) // 3
# a = a.astype(jnp.int32)

In [6]:
# a.dtype

In [7]:
from jax import vmap
from functools import partial
@partial(vmap, in_axes=(0,None))
@partial(vmap, in_axes=(None,0))
def f(x,y):
    return jnp.dot(x-y,x-y)

In [8]:
X = jnp.arange(5,dtype=jnp.float32).reshape(-1,1)
Y = jnp.arange(5,dtype=jnp.float32).reshape(-1,1)
print(X)
print(Y)
print(f(X,Y))

[[0.]
 [1.]
 [2.]
 [3.]
 [4.]]
[[0.]
 [1.]
 [2.]
 [3.]
 [4.]]
[[ 0.  1.  4.  9. 16.]
 [ 1.  0.  1.  4.  9.]
 [ 4.  1.  0.  1.  4.]
 [ 9.  4.  1.  0.  1.]
 [16.  9.  4.  1.  0.]]


In [7]:
from gaussian_process.kernels import RBF

In [8]:
class Test:
    def __init__(self) -> None:
        self.kernel = RBF()

    @partial(vmap, in_axes=(None,0,None,None))
    @partial(vmap, in_axes=(None,None,0,None))
    def f(self,x,y,index):
        return self.kernel.eval_dx2(x,y,index)

NameError: name 'partial' is not defined

In [ ]:
T = Test()
print(T.f(X,X,0))

[[ 0.         -0.60653067 -0.27067056 -0.03332699 -0.00134185]
 [ 0.60653067  0.         -0.60653067 -0.27067056 -0.03332699]
 [ 0.27067056  0.60653067  0.         -0.60653067 -0.27067056]
 [ 0.03332699  0.27067056  0.60653067  0.         -0.60653067]
 [ 0.00134185  0.03332699  0.27067056  0.60653067  0.        ]]


In [9]:

x = jnp.arange(20).reshape(4,5)

In [ ]:
def f(x):
    A = jnp.arange(25).reshape(5,5)
    return x@A@x.T

DeviceArray([[ 1800,  6050, 10300, 14550],
             [ 5050, 16800, 28550, 40300],
             [ 8300, 27550, 46800, 66050],
             [11550, 38300, 65050, 91800]], dtype=int32)